### PR TITLE
Add Win32 support.

### PR DESCRIPTION
**Pull request by plicease**
This should now address the issues that I mentioned in #10

### CODE REVIEW

**Comment by cosimo** [comment]
Really nice! I'm going to test it asap.

**Comment by plicease** [comment]
@cosimo there is a bug in the current `Alien::Base` that will probably prevent this from working.  I should have a dev release this week, but if you see this bug and want to try this out now, you can install AB from git, or I can create a tarball for you.

https://github.com/Perl5-Alien/Alien-Base/pull/139

**Comment by plicease** [comment]
Just an update on the AB windows bug.  I put a dev version of AB on CPAN this weekend:

https://metacpan.org/pod/release/PLICEASE/Alien-Base-0.023_01/lib/Alien/Base.pm

I expect to do a production release on Wednesday, assuming the tester matrix still looks good (right now it looks great).  If you wanted to verify this works now then you'd want to use the dev version of AB, otherwise you can wait till Wednesday and use the prod version when it goes out.

**Comment by plicease** [comment]
When you get a chance, could you please cut a new release?  Alien::Base 0.024 has been released to CPAN includes the windows fixes that should make this just work without installing any libraries or patching any modules :)

**Comment by cosimo** [comment]
You mean that the next Text::Hunspell should require Alien::Base >= 0.024 ?

**Comment by plicease** [comment]
If you wanted.  I could also put a dynamic prereq into Alien::Hunspell to require 0.024 on windows only.

**Comment by plicease** [comment]
I made 0.024 a prereq for `Alien::Hunspell` 

https://github.com/plicease/Alien-Hunspell/commit/8cb4102bb0a354e8003f9b1c95d0322ace598375

I have to do one more dev release before I ship it as prod to CPAN, but I expect to do that within the week.

There is no harm in shipping the current `Text::Hunspell` as is, but you may want to wait until the next version of `Alien::Hunspell` and require that one instead.

**Comment by cosimo** [comment]
Will the next Alien::Hunspell be 0.04?

**Comment by plicease** [comment]
Yes.  I will let you know as soon as it is on CPAN.

**Comment by cosimo** [comment]
Released 2.13 now anyway, since it was a good and just release to be had :-)
As soon as A::H 0.04 is out, I will release a 2.14 that requires it.

**Comment by plicease** [comment]
0.04 is on its way to CPAN.  Thanks again for working with me on this.  I am excited to have Text::Hunspell working in strawberry.

**Comment by cosimo** [comment]
Can you please have a look at the new Makefile.PL in 2.14? I haven't released it to CPAN yet, but plan to do so. I just have a small doubt about making the Alien::Hunspell dependency explicit to version 0.04 in the first lines of Makefile.PL, rather than only in CONFIGURE_REQUIRES.

https://github.com/cosimo/perl5-text-hunspell/commit/d06e8dafa8b0dee7809428de371aef9cf97bb660

**Comment by plicease** [comment]
I actually think it is a good thing to include the requirement in both places.  Some cpan clients and cpantesters boxes will ignore specific version prerequsites if they have an older version installed, and if the newer version fails to install.  I personally find this annoying, but have learned to live with it.  If you specify the version in the use line the `Makefile.PL`, then it won't even compile without the proper version of `Alien::Hunspell`, and thus you won't get any cpantesters failures due to the wrong version.

**Comment by cosimo** [comment]
2.14 is on its way to CPAN.
Thanks for your amazing work here.

**Pull request merged**
